### ISSUE TITLE
impl(ghc < 8.0) dependencies should not output

### ISSUE THREAD

**Issue by felixonmars** [berberman/arch-hs#10]
Considering `quickcheck-classes-base 0.6.0.0 0.6.1.0`:

Actual cabal change:
![2020-09-15-004736-deb9c4](https://user-images.githubusercontent.com/1006477/93114393-206e4100-f6ed-11ea-99e9-1e7639e2fce3.png)

arch-hs-diff output:
![2020-09-15-004817-2bd478](https://user-images.githubusercontent.com/1006477/93114427-2c5a0300-f6ed-11ea-877c-61e66ea9315d.png)

**Comment by felixonmars** [comment]
Expected behavior: `semigroups` should be shown as a removed dependency in the new version (a diff item).

**Comment by berberman** [comment]
It's essentially a display error...

**Comment by felixonmars** [comment]
> It's essentially a display error...

Confirmed the fix. Many thanks!
