### ISSUE TITLE
Machine parsable output

### ISSUE THREAD

**Issue by VannTen** [berberman/arch-hs#36]
# Feature request

Would adding a option to have machine parseable output possible ?
I'm thinking in particular to the Recommended package order. (a simple text file
with the package in the order ?)
And maybe a json file for the dependency graph ?

Your tool is fantastic, by the way o/

Thank you for your work :)

**Comment by berberman** [comment]
Hi, I implemented dumping the output to undecorated JSON, like [this](https://pastebin.com/QMTJ4vc1) (`arch-hs --json ./output.json gi-gdk`, the example in README): 
Does this satisfy your needs? Or do you have any suggestions ;)

**Comment by VannTen** [comment]
Exactly what I had in mind ! Thank you very much :)

**Comment by berberman** [comment]
The latest release 0.7.0 has included this feature, so I'm going to close it.
