### ISSUE TITLE
Special case licenses

### ISSUE THREAD

**Issue by felixonmars** [berberman/arch-hs#59]
According to our [guidelines](https://wiki.archlinux.org/title/PKGBUILD#license), licenses like [BSD](https://en.wikipedia.org/wiki/BSD_License), [ISC](https://en.wikipedia.org/wiki/ISC_license), [MIT](https://en.wikipedia.org/wiki/MIT_License) should not be prefixed by "custom:" although they are not provided in the system. The license should still be installed inside the package, just the `custom:` prefix should be removed.

**Comment by berberman** [comment]
arch-hs reuses the licenses definition in arch-web: https://github.com/berberman/arch-web/blob/039b541acc9576252283405c9a9d069c7b1bf67a/src/Web/ArchLinux/Types.hs#L97. Thus we might need to make changes on that repo.
