### ISSUE TITLE
Reference Cabal Environmental Variables

### ISSUE THREAD

**Issue by XVicarious** [berberman/arch-hs#65]
https://github.com/berberman/arch-hs/blob/94ad1bd361ebb40be5ce82b357a4df3ea4cea823/src/Distribution/ArchHs/Hackage.hs#L39

This is a hard-coded path to `CABAL_DIR`, which can be changed by the user. It would be helpful to reference the variable or to have a flag to change where we look for Cabal's files.

**Comment by berberman** [comment]
There is a CLI option `-h` to specify the path to hackage database.
